config/routes.rb
Rails.application.routes.draw do
  resources :policy_extensions
  root 'policy_extensions#index'
  get 'account_resolutions/new'

  get 'account_resolutions/create'

  resources :policies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/policy_extension.rb
class PolicyExtension < ApplicationRecord
  octopus_establish_connection(:adapter => "mysql2", :database => "fgen", :host => "localhost", :port => "3306", :username => "fgen", :password => "fortunegeneral")

  before_save :compute_new_due_date

  def compute_new_due_date
    self.new_due_date = orig_due_date + extension
  end
end

app/controllers/policy_extensions_controller.rb
class PolicyExtensionsController < ApplicationController
  before_action :set_policy_extension, only: [:show, :edit, :update, :destroy]

  # GET /policy_extensions
  # GET /policy_extensions.json
  def index
    @policy_extensions = PolicyExtension.all
  end

  # GET /policy_extensions/1
  # GET /policy_extensions/1.json
  def show
  end

  # GET /policy_extensions/new
  def new
    # @policy = Policy.find(params[:id])
    @policy_extension = PolicyExtension.new
  end

  # GET /policy_extensions/1/edit
  def edit
  end

  # POST /policy_extensions
  # POST /policy_extensions.json
  def create
    @policy_extension = PolicyExtension.new(policy_extension_params)

    respond_to do |format|
      if @policy_extension.save
        format.html { redirect_to @policy_extension, notice: 'Policy extension was successfully created.' }
        format.json { render :show, status: :created, location: @policy_extension }
      else
        format.html { render :new }
        format.json { render json: @policy_extension.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /policy_extensions/1
  # PATCH/PUT /policy_extensions/1.json
  def update
    respond_to do |format|
      if @policy_extension.update(policy_extension_params)
        format.html { redirect_to @policy_extension, notice: 'Policy extension was successfully updated.' }
        format.json { render :show, status: :ok, location: @policy_extension }
      else
        format.html { render :edit }
        format.json { render json: @policy_extension.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /policy_extensions/1
  # DELETE /policy_extensions/1.json
  def destroy
    @policy_extension.destroy
    respond_to do |format|
      format.html { redirect_to policy_extensions_url, notice: 'Policy extension was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_policy_extension
      @policy_extension = PolicyExtension.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def policy_extension_params
      params.require(:policy_extension).permit(:policy_no, :endorsement_no, :assured_no, :intermediary_no, :intermediary_name, :effective_date, :premium_due, :credit_term, :orig_due_date, :extension, :new_due_date)
    end
end

app/helpers/policy_extensions_helper.rb
module PolicyExtensionsHelper
end

app/views/policy_extensions/_form.html.erb
<%= simple_form_for(@policy_extension) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :policy_no, input_html: { value: @policy.no } %>
    <%= f.input :endorsement_no, input_html: {value: @policy.endorsement_no} %>
    <%= f.input :assured_no, input_html: {value: @policy.assured.id} %>
    <%= f.input :intermediary_no, input_html: {value: @policy.intermediary&.intm_no} %>
    <%= f.input :intermediary_name, input_html: {value: @policy.intermediary&.name} %>
    <%= f.input :effective_date, as: :string, input_html:{ value: format_date(@policy.eff_date) } %>
    <%= f.input :premium_due, input_html:{ value: @policy.prem_amt} %>
    <%= f.input :credit_term, input_html:{ value: @policy.intermediary.credit_term} %>
    <%= f.input :orig_due_date, as: :string, input_html:{ value: format_date(@policy.due_date) } %>
    <%= f.input :extension %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/policy_extensions/edit.html.erb
<h1>Editing Policy Extension</h1>

<%= render 'form', policy_extension: @policy_extension %>

<%= link_to 'Show', @policy_extension %> |
<%= link_to 'Back', policy_extensions_path %> |
<%= link_to 'Home', policies_path %>

app/views/policy_extensions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Policy Extensions</h1>

<table>
  <thead>
    <tr>
      <th>Policy no</th>
      <th>Endorsement no</th>
      <th>Assured no</th>
      <th>Intermediary no</th>
      <th>Intermediary name</th>
      <th>Effective date</th>
      <th>Premium due</th>
      <th>Credit term</th>
      <th>Orig due date</th>
      <th>Extension</th>
      <th>New due date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @policy_extensions.each do |policy_extension| %>
      <tr>
        <td><%= policy_extension.policy_no %></td>
        <td><%= policy_extension.endorsement_no %></td>
        <td><%= policy_extension.assured_no %></td>
        <td><%= policy_extension.intermediary_no %></td>
        <td><%= policy_extension.intermediary_name %></td>
        <td><%= policy_extension.effective_date %></td>
        <td><%= policy_extension.premium_due %></td>
        <td><%= policy_extension.credit_term %></td>
        <td><%= policy_extension.orig_due_date %></td>
        <td><%= policy_extension.extension %></td>
        <td><%= policy_extension.new_due_date %></td>
        <td><%= link_to 'Show', policy_extension %></td>
        <td><%= link_to 'Edit', edit_policy_extension_path(policy_extension) %></td>
        <td><%= link_to 'Destroy', policy_extension, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Policy Extension', new_policy_extension_path %>

app/views/policy_extensions/new.html.erb
<h1>New Policy Extension</h1>

<%= render 'form', policy_extension: @policy_extension %>

<%= link_to 'Back', policy_extensions_path %> |
<%= link_to 'Home', policies_path %>

app/views/policy_extensions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Policy no:</strong>
  <%= @policy_extension.policy_no %>
</p>

<p>
  <strong>Endorsement no:</strong>
  <%= @policy_extension.endorsement_no %>
</p>

<p>
  <strong>Assured no:</strong>
  <%= @policy_extension.assured_no %>
</p>

<p>
  <strong>Intermediary no:</strong>
  <%= @policy_extension.intermediary_no %>
</p>

<p>
  <strong>Intermediary name:</strong>
  <%= @policy_extension.intermediary_name %>
</p>

<p>
  <strong>Effective date:</strong>
  <%= @policy_extension.effective_date %>
</p>

<p>
  <strong>Premium due:</strong>
  <%= @policy_extension.premium_due %>
</p>

<p>
  <strong>Credit term:</strong>
  <%= @policy_extension.credit_term %>
</p>

<p>
  <strong>Orig due date:</strong>
  <%= @policy_extension.orig_due_date %>
</p>

<p>
  <strong>Extension:</strong>
  <%= @policy_extension.extension %>
</p>

<p>
  <strong>New due date:</strong>
  <%= @policy_extension.new_due_date %>
</p>

<%= link_to 'Edit', edit_policy_extension_path(@policy_extension) %> |
<%= link_to 'Back', policy_extensions_path %>|
<%= link_to 'Home', policies_path %>